In [ ]:
import numpy as np

arr1=np.array([0,1,2,3,4,5])
arr2=np.array([3,6,7,8,9,0])
result= arr1+arr2
print(result)

[ 3  7  9 11 13  5]


In [1]:
import numpy as np

arr1=np.array([0,1,2,3,4,5])

result= arr1*3
print(result)

[ 0  3  6  9 12 15]


In [ ]:
import numpy as np

arr1=np.array([0,1,2,3,4,5])
result=arr1/2
print(result)

[0.  0.5 1.  1.5 2.  2.5]


In [ ]:
import numpy as np

arr1=np.array([0,1,2,3,4,5])

reversed_array =np.flip(arr1)
print(reversed_array)


[5 4 3 2 1 0]


In [4]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])


unique, counts = np.unique(x, return_counts=True)
most_frequent_value = unique[np.argmax(counts)]
indices = np.where(x == most_frequent_value)[0]

print("Most Frequent Value in x:", most_frequent_value)
print("Indices of Most Frequent Value in x:", indices)

Most Frequent Value in x: 1
Indices of Most Frequent Value in x: [0 5 7 8 9]


In [3]:
import numpy as np

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])


unique, counts = np.unique(y, return_counts=True)
most_frequent_value = unique[np.argmax(counts)]
indices = np.where(y == most_frequent_value)[0]

print("Most Frequent Value in y:", most_frequent_value)
print("Indices of Most Frequent Value in y:", indices)

Most Frequent Value in y: 1
Indices of Most Frequent Value in y: [0 1 2]


In [2]:
import numpy as np
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[0][1])

print(arr[2][0])

20
70


In [5]:
import numpy as np


Adhya = np.linspace(10, 100, 25)


print("Array:", Adhya)
print("Dimensions:", Adhya.ndim)
print("Shape:", Adhya.shape)
print("Total elements:", Adhya.size)
print("Data type:", Adhya.dtype)
print("Total bytes consumed:", Adhya.nbytes)


transposed_array = Adhya.reshape(25, 1)
print("Transposed Array using reshape:\n", transposed_array)


try:
    print("Transposed Array using .T:\n", Adhya.T)
except Exception as e:
    print("Error using .T:", e)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes consumed: 200
Transposed Array using reshape:
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transposed Array using .T:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [6]:
import numpy as np


ucs420_Adhya = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])


print("Mean:", np.mean(ucs420_Adhya))
print("Median:", np.median(ucs420_Adhya))
print("Max:", np.max(ucs420_Adhya))
print("Min:", np.min(ucs420_Adhya))
print("Unique Elements:", np.unique(ucs420_Adhya))


reshaped_ucs420_Adhya = ucs420_Adhya.reshape(4, 3)
print("Reshaped Array (4x3):\n", reshaped_ucs420_Adhya)


resized_ucs420_Adhya = np.resize(ucs420_Adhya, (2, 3))
print("Resized Array (2x3):\n", resized_ucs420_Adhya)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array (2x3):
 [[10 20 30]
 [40 50 60]]
